---
version: '2'

template:
  name: "v2 attempt"
  description: "Native v2 format"
  required:
   - build
   - repo

toolchain:
  name: "initial-name"

services:
  repo:
    service_id: githubpublic
    schema:
      $ref: github.json
    parameters:
      repo_name: "da name, {{services.repo.parameters.repo_url}}"
      repo_url: "da url"
      type: clone
      has_issues: true

  build:
    # Note deploy.json is invalid
    schema:
      $ref: deploy.json
    service_id: pipeline
    parameters:
      magic:
        description: "{{description}}"
        name: "{{name}}"
        organization: "{{organization}}"
        region: "{{region}}"
        space: "{{space}}"
        timestamp: "{{timestamp}}"
      ref:
        simple: "{{services.repo.parameters.repo_url}}"
        expr:   "pre-{{services.repo.parameters.repo_url}}-post"
        to-ref: "{{services.repo.parameters.repo_name}}"
      context:
        fizz: "{{fizz}}"
