---
version: 3

template:
  name: "v2 attempt"
  description: "Native v2 format"
  required:
   - deploy
   - repo

toolchain:
  name: "initial-name"

services:
  repo:
    service_id: githubpublic
    schema:
      $ref: github.json
    parameters:
      repo_name: "da name, {{repo.parameters.repo_url}}"
      repo_url: "da url"
      type: clone
      has_issues: true

  build:
    schema:
      $ref: deploy.json
    service_id: pipeline
    parameters:
      magic:
        baseName: "{{baseName}}"
        description: "{{description}}"
        name: "{{name}}"
        organization: "{{organization}}"
        region: "{{region}}"
        space: "{{space}}"
        timestamp: "{{timestamp}}"
      ref:
        simple: "{{repo.parameters.repo_url}}"
        expr:   "pre-{{repo.parameters.repo_url}}-post"
        to-ref: "{{repo.parameters.repo_name}}"
      context:
        fizz: "{{fizz}}"

# TODO test refs inside a service-category
# deploy:
#   schema: deploy.json
#   service-category: pipeline
#   parameters:
